name: klingon-serial-unit-tests

on: 
    push:
    workflow_dispatch:
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
        BRANCH: ${{ github.ref }}
        GITHUB_USERNAME: ${{ github.actor }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Set up Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: |
        poetry install

    - name: Build and test klingon-serial
      run: |
        poetry run make sdist
        poetry run make wheel
        poetry run make test

    - name: Test OpenFaaS function
      run: |
        poetry run pytest -v openfaas/
